services:
  opengauss:
    image: enmotech/opengauss:latest
    container_name: opengauss_experiment
    privileged: true
    ports:
      - "5432:5432"
    environment:
      - GS_PASSWORD=Enmo@123
      - GS_NODENAME=opengauss
      - GS_DB=foreign_key_experiment
    volumes:
      - opengauss_data:/var/lib/opengauss/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: "no"
    shm_size: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  opengauss_data:
